global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "telemetry"
    static_configs:
      - targets:
          - ingest:9696

  - job_name: "grafana-image-rendering-service"
    static_configs:
      - targets:
          - renderer:8081
